package org.motechproject.hub.model.hibernate;

// Generated Apr 11, 2014 3:15:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HubDistributionStatus generated by hbm2java
 */
@Entity
@Table(name = "hub_distribution_status", schema = "hub")
public class HubDistributionStatus implements java.io.Serializable {

	private Long distributionStatusId;
	private String distributionStatusCode;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;
	private Set<HubSubscriberTransaction> hubSubscriberTransactions = new HashSet<HubSubscriberTransaction>(
			0);

	public HubDistributionStatus() {
	}

	public HubDistributionStatus(Long distributionStatusId,
			String distributionStatusCode) {
		this.distributionStatusId = distributionStatusId;
		this.distributionStatusCode = distributionStatusCode;
	}

	public HubDistributionStatus(Long distributionStatusId,
			String distributionStatusCode, Date createTime, Date lastUpdated,
			String createdBy, String lastUpdatedBy,
			Set<HubSubscriberTransaction> hubSubscriberTransactions) {
		this.distributionStatusId = distributionStatusId;
		this.distributionStatusCode = distributionStatusCode;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.hubSubscriberTransactions = hubSubscriberTransactions;
	}

	@Id
	@Column(name = "distribution_status_id", unique = true, nullable = false)
	public Long getDistributionStatusId() {
		return this.distributionStatusId;
	}

	public void setDistributionStatusId(Long distributionStatusId) {
		this.distributionStatusId = distributionStatusId;
	}

	@Column(name = "distribution_status_code", nullable = false, length = 15)
	public String getDistributionStatusCode() {
		return this.distributionStatusCode;
	}

	public void setDistributionStatusCode(String distributionStatusCode) {
		this.distributionStatusCode = distributionStatusCode;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "create_time", length = 15)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "last_updated", length = 15)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hubDistributionStatus")
	public Set<HubSubscriberTransaction> getHubSubscriberTransactions() {
		return this.hubSubscriberTransactions;
	}

	public void setHubSubscriberTransactions(
			Set<HubSubscriberTransaction> hubSubscriberTransactions) {
		this.hubSubscriberTransactions = hubSubscriberTransactions;
	}

}
