package org.motechproject.hub.model.hibernate;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HubDistributionError generated by hbm2java
 */
@Entity
@Table(name = "hub_distribution_error", schema = "hub")
public class HubDistributionError implements java.io.Serializable {

	private static final long serialVersionUID = 7299910171961544671L;
	
	private long distributionErrorId;
	private HubSubscription hubSubscription;
	private String errorDescription;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;

	public HubDistributionError() {
	}

	public HubDistributionError(long distributionErrorId,
			HubSubscription hubSubscription) {
		this.distributionErrorId = distributionErrorId;
		this.hubSubscription = hubSubscription;
	}

	public HubDistributionError(long distributionErrorId,
			HubSubscription hubSubscription, String errorDescripion,
			Date createTime, Date lastUpdated, String createdBy,
			String lastUpdatedBy) {
		this.distributionErrorId = distributionErrorId;
		this.hubSubscription = hubSubscription;
		this.errorDescription = errorDescripion;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@Column(name = "distribution_error_id", unique = true, nullable = false)
	public long getDistributionErrorId() {
		return this.distributionErrorId;
	}

	public void setDistributionErrorId(long distributionErrorId) {
		this.distributionErrorId = distributionErrorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subscription_id", nullable = false)
	public HubSubscription getHubSubscription() {
		return this.hubSubscription;
	}

	public void setHubSubscription(HubSubscription hubSubscription) {
		this.hubSubscription = hubSubscription;
	}

	@Column(name = "error_description", length = 150)
	public String getErrorDescription() {
		return errorDescription;
	}

	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "create_time", length = 15)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "last_updated", length = 15)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
