package org.motechproject.hub.model.hibernate;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HubPublisherTransaction generated by hbm2java
 */
@Entity
@Table(name = "hub_publisher_transaction", schema = "hub")
public class HubPublisherTransaction implements java.io.Serializable {

	private static final long serialVersionUID = -8125937765866045050L;
	
	private long publisherTransactionId;
	private HubTopic hubTopic;
	private Date notificationTime;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;

	public HubPublisherTransaction() {
	}

	public HubPublisherTransaction(long publisherTransactionId,
			HubTopic hubTopic, Date notificationTime) {
		this.publisherTransactionId = publisherTransactionId;
		this.hubTopic = hubTopic;
		this.notificationTime = notificationTime;
	}

	public HubPublisherTransaction(long publisherTransactionId,
			HubTopic hubTopic, Date notificationTime, Date createTime,
			Date lastUpdated, String createdBy, String lastUpdatedBy) {
		this.publisherTransactionId = publisherTransactionId;
		this.hubTopic = hubTopic;
		this.notificationTime = notificationTime;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@Column(name = "publisher_transaction_id", unique = true, nullable = false)
	public long getPublisherTransactionId() {
		return this.publisherTransactionId;
	}

	public void setPublisherTransactionId(long publisherTransactionId) {
		this.publisherTransactionId = publisherTransactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id", nullable = false)
	public HubTopic getHubTopic() {
		return this.hubTopic;
	}

	public void setHubTopic(HubTopic hubTopic) {
		this.hubTopic = hubTopic;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "notification_time", nullable = false, length = 15)
	public Date getNotificationTime() {
		return this.notificationTime;
	}

	public void setNotificationTime(Date notificationTime) {
		this.notificationTime = notificationTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "create_time", length = 15)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "last_updated", length = 15)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
