package org.motechproject.hub.model.hibernate;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HubSubscription generated by hbm2java
 */
@Entity
@Table(name = "hub_subscription", schema = "hub")
public class HubSubscription implements java.io.Serializable {

	private static final long serialVersionUID = 811889421861700076L;
	
	private long subscriptionId;
	private HubTopic hubTopic;
	private HubSubscriptionStatus hubSubscriptionStatus;
	private String callbackUrl;
	private Long leaseSeconds;
	private String secret;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;
	private Set<HubDistributionError> hubDistributionErrors = new HashSet<HubDistributionError>(
			0);
	private Set<HubSubscriberTransaction> hubSubscriberTransactions = new HashSet<HubSubscriberTransaction>(
			0);

	public HubSubscription() {
	}

	public HubSubscription(long subscriptionId, HubTopic hubTopic,
			HubSubscriptionStatus hubSubscriptionStatus, String callbackUrl) {
		this.subscriptionId = subscriptionId;
		this.hubTopic = hubTopic;
		this.hubSubscriptionStatus = hubSubscriptionStatus;
		this.callbackUrl = callbackUrl;
	}

	public HubSubscription(long subscriptionId, HubTopic hubTopic,
			HubSubscriptionStatus hubSubscriptionStatus, String callbackUrl,
			Long leaseSeconds, String secret, Date createTime,
			Date lastUpdated, String createdBy, String lastUpdatedBy,
			Set<HubDistributionError> hubDistributionErrors,
			Set<HubSubscriberTransaction> hubSubscriberTransactions) {
		this.subscriptionId = subscriptionId;
		this.hubTopic = hubTopic;
		this.hubSubscriptionStatus = hubSubscriptionStatus;
		this.callbackUrl = callbackUrl;
		this.leaseSeconds = leaseSeconds;
		this.secret = secret;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.hubDistributionErrors = hubDistributionErrors;
		this.hubSubscriberTransactions = hubSubscriberTransactions;
	}

	@Id
	@Column(name = "subscription_id", unique = true, nullable = false)
	public long getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(long subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id", nullable = false)
	public HubTopic getHubTopic() {
		return this.hubTopic;
	}

	public void setHubTopic(HubTopic hubTopic) {
		this.hubTopic = hubTopic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subscription_status_id", nullable = false)
	public HubSubscriptionStatus getHubSubscriptionStatus() {
		return this.hubSubscriptionStatus;
	}

	public void setHubSubscriptionStatus(
			HubSubscriptionStatus hubSubscriptionStatus) {
		this.hubSubscriptionStatus = hubSubscriptionStatus;
	}

	@Column(name = "callback_url", nullable = false)
	public String getCallbackUrl() {
		return this.callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}

	@Column(name = "lease_seconds")
	public Long getLeaseSeconds() {
		return this.leaseSeconds;
	}

	public void setLeaseSeconds(Long leaseSeconds) {
		this.leaseSeconds = leaseSeconds;
	}

	@Column(name = "secret")
	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "create_time", length = 15)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "last_updated", length = 15)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hubSubscription")
	public Set<HubDistributionError> getHubDistributionErrors() {
		return this.hubDistributionErrors;
	}

	public void setHubDistributionErrors(
			Set<HubDistributionError> hubDistributionErrors) {
		this.hubDistributionErrors = hubDistributionErrors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hubSubscription")
	public Set<HubSubscriberTransaction> getHubSubscriberTransactions() {
		return this.hubSubscriberTransactions;
	}

	public void setHubSubscriberTransactions(
			Set<HubSubscriberTransaction> hubSubscriberTransactions) {
		this.hubSubscriberTransactions = hubSubscriberTransactions;
	}

}
