package org.motechproject.hub.model.hibernate;

// Generated Apr 11, 2014 3:15:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HubSubscriptionStatus generated by hbm2java
 */
@Entity
@Table(name = "hub_subscription_status", schema = "hub")
public class HubSubscriptionStatus implements java.io.Serializable {

	private Long subscriptionStatusId;
	private String subscriptionStatusCode;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;
	private Set<HubSubscription> hubSubscriptions = new HashSet<HubSubscription>(
			0);

	public HubSubscriptionStatus() {
	}

	public HubSubscriptionStatus(Long subscriptionStatusId,
			String subscriptionStatusCode) {
		this.subscriptionStatusId = subscriptionStatusId;
		this.subscriptionStatusCode = subscriptionStatusCode;
	}

	public HubSubscriptionStatus(Long subscriptionStatusId,
			String subscriptionStatusCode, Date createTime, Date lastUpdated,
			String createdBy, String lastUpdatedBy,
			Set<HubSubscription> hubSubscriptions) {
		this.subscriptionStatusId = subscriptionStatusId;
		this.subscriptionStatusCode = subscriptionStatusCode;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.hubSubscriptions = hubSubscriptions;
	}

	@Id
	@Column(name = "subscription_status_id", unique = true, nullable = false)
	public Long getSubscriptionStatusId() {
		return this.subscriptionStatusId;
	}

	public void setSubscriptionStatusId(Long subscriptionStatusId) {
		this.subscriptionStatusId = subscriptionStatusId;
	}

	@Column(name = "subscription_status_code", nullable = false, length = 15)
	public String getSubscriptionStatusCode() {
		return this.subscriptionStatusCode;
	}

	public void setSubscriptionStatusCode(String subscriptionStatusCode) {
		this.subscriptionStatusCode = subscriptionStatusCode;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "create_time", length = 15)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "last_updated", length = 15)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hubSubscriptionStatus")
	public Set<HubSubscription> getHubSubscriptions() {
		return this.hubSubscriptions;
	}

	public void setHubSubscriptions(Set<HubSubscription> hubSubscriptions) {
		this.hubSubscriptions = hubSubscriptions;
	}

}
