package org.motechproject.event.messaging;

import org.motechproject.event.MotechEvent;

/**
 * Sends <code>MotechEvent</code> to the ActiveMQ broker, the implementation is generated by Spring Integration.
 */
public interface OutboundEventGateway {

    /**
     *  Sends the motechEvent's message as a payload to the message channel
     *  defined in the Spring Integration configuration file. The channel is
     *  connected with a message queue, meaning only one Motech instance will
     *  receive this event.
     *
     * @param motechEvent the event to be sent
     */
    void sendEventMessage(MotechEvent motechEvent);

    /**
     *  Broadcast the motechEvent's message as a payload to the message channel
     *  defined in the Spring Integration configuration file. The channel is
     *  connected with a message topic, meaning all Motech instances will receive
     *  this event.
     *
     * @param motechEvent the event to be broadcast
     */
    void broadcastEventMessage(MotechEvent motechEvent);
}
