package org.motechproject.hub.mds;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1


import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * HubDistributionError generated by hbm2java
 */
@Entity
public class HubDistributionError implements java.io.Serializable {

	private static final long serialVersionUID = 7299910171961544671L;
	
	@Field(required = true)
	private Integer hubSubscriptionId;
	
	@Field
	private String errorDescription;


	public Integer getHubSubscriptionId() {
		return hubSubscriptionId;
	}

	public void setHubSubscriptionId(Integer hubSubscriptionId) {
		this.hubSubscriptionId = hubSubscriptionId;
	}

	public String getErrorDescription() {
		return errorDescription;
	}

	public void setErrorDescription(String errorDescription) {
		this.errorDescription = errorDescription;
	}

	public HubDistributionError() {
	}

	public HubDistributionError(
			Integer hubSubscriptionId) {
		this.hubSubscriptionId = hubSubscriptionId;
	}

	public HubDistributionError(
			Integer hubSubscriptionId , String errorDescripion
			) {
		this.hubSubscriptionId = hubSubscriptionId;
		this.errorDescription = errorDescripion;
		
	}

	
}
