package org.motechproject.hub.mds;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1


import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;



/**
 * HubSubscription generated by hbm2java
 */
@Entity
public class HubSubscription implements java.io.Serializable {

	private static final long serialVersionUID = 811889421861700076L;
	
	//TODO this should be an int ..not supported by mds
	@Field(required=true)
	private String hubTopicId;
	
	//TODO this should be an int ..not supported by mds
	
	@Field(required=true)
	private String hubSubscriptionStatusId;
	
	@Field(required=true)
	private String callbackUrl;
	
	//TODO this should be an int ..not supported by mds
	@Field
	private String leaseSeconds;
	
	@Field
	private String secret;
	
	public String getHubTopicId() {
		return hubTopicId;
	}

	public void setHubTopicId(String hubTopicId) {
		this.hubTopicId = hubTopicId;
	}

	public String getHubSubscriptionStatusId() {
		return hubSubscriptionStatusId;
	}

	public void setHubSubscriptionStatusId(String hubSubscriptionStatusId) {
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
	}

	public String getCallbackUrl() {
		return callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}

	public String getLeaseSeconds() {
		return leaseSeconds;
	}

	public void setLeaseSeconds(String leaseSeconds) {
		this.leaseSeconds = leaseSeconds;
	}

	public String getSecret() {
		return secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	
	
	
	public HubSubscription() {
	}

	public HubSubscription(String  hubTopicId,
			String hubSubscriptionStatusId, String callbackUrl) {
		this.hubTopicId = hubTopicId;
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
		this.callbackUrl = callbackUrl;
	}

	public HubSubscription(String  hubTopicId,
			String hubSubscriptionStatusId, String callbackUrl,
			String leaseSeconds, String secret) {
		this.hubTopicId = hubTopicId;
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
		this.callbackUrl = callbackUrl;
		this.leaseSeconds = leaseSeconds;
		this.secret = secret;
		
	}

	

}
