package org.motechproject.hub.mds;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1


import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;



/**
 * HubSubscription generated by hbm2java
 */
@Entity
public class HubSubscription implements java.io.Serializable {

	private static final long serialVersionUID = 811889421861700076L;
	
	@Field(required=true)
	private int hubTopicId;
	
	public int getHubTopicId() {
		return hubTopicId;
	}

	public void setHubTopicId(int hubTopicId) {
		this.hubTopicId = hubTopicId;
	}

	public int getHubSubscriptionStatusId() {
		return hubSubscriptionStatusId;
	}

	public void setHubSubscriptionStatusId(int hubSubscriptionStatusId) {
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
	}

	public String getCallbackUrl() {
		return callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}

	public Long getLeaseSeconds() {
		return leaseSeconds;
	}

	public void setLeaseSeconds(Long leaseSeconds) {
		this.leaseSeconds = leaseSeconds;
	}

	public String getSecret() {
		return secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	@Field(required=true)
	private int hubSubscriptionStatusId;
	
	@Field(required=true)
	private String callbackUrl;
	
	@Field
	private Long leaseSeconds;
	
	@Field
	private String secret;
	
	
	public HubSubscription() {
	}

	public HubSubscription(int  hubTopicId,
			int hubSubscriptionStatusId, String callbackUrl) {
		this.hubTopicId = hubTopicId;
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
		this.callbackUrl = callbackUrl;
	}

	public HubSubscription(int  hubTopicId,
			int hubSubscriptionStatusId, String callbackUrl,
			Long leaseSeconds, String secret) {
		this.hubTopicId = hubTopicId;
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
		this.callbackUrl = callbackUrl;
		this.leaseSeconds = leaseSeconds;
		this.secret = secret;
		
	}

	

}
