package org.motechproject.hub.mds;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1


import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;



/**
 * HubSubscription generated by hbm2java
 */
@Entity
public class HubSubscription implements java.io.Serializable {

	private static final long serialVersionUID = 811889421861700076L;
	
	//TODO this should be an Integer ..not supported by mds
	@Field(required=true)
	private Integer hubTopicId;
	
	//TODO this should be an Integer ..not supported by mds
	
	@Field(required=true)
	private Integer hubSubscriptionStatusId;
	
	@Field(required=true)
	private String callbackUrl;
	
	//TODO this should be an Integer ..not supported by mds
	@Field
	private Integer leaseSeconds;
	
	@Field
	private String secret;
	
	public Integer getHubTopicId() {
		return hubTopicId;
	}

	public void setHubTopicId(Integer hubTopicId) {
		this.hubTopicId = hubTopicId;
	}

	public Integer getHubSubscriptionStatusId() {
		return hubSubscriptionStatusId;
	}

	public void setHubSubscriptionStatusId(Integer hubSubscriptionStatusId) {
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
	}

	public String getCallbackUrl() {
		return callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}

	public Integer getLeaseSeconds() {
		return leaseSeconds;
	}

	public void setLeaseSeconds(Integer leaseSeconds) {
		this.leaseSeconds = leaseSeconds;
	}

	public String getSecret() {
		return secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	
	
	
	public HubSubscription() {
	}

	public HubSubscription(Integer  hubTopicId,
			Integer hubSubscriptionStatusId, String callbackUrl) {
		this.hubTopicId = hubTopicId;
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
		this.callbackUrl = callbackUrl;
	}

	public HubSubscription(Integer  hubTopicId,
			Integer hubSubscriptionStatusId, String callbackUrl,
			Integer leaseSeconds, String secret) {
		this.hubTopicId = hubTopicId;
		this.hubSubscriptionStatusId = hubSubscriptionStatusId;
		this.callbackUrl = callbackUrl;
		this.leaseSeconds = leaseSeconds;
		this.secret = secret;
		
	}

	

}
