package org.motechproject.hub.mds;

// Generated Apr 21, 2014 1:51:45 PM by Hibernate Tools 3.4.0.CR1

import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * HubSubscriptionStatus generated by hbm2java
 */
@Entity
public class HubSubscriptionStatus implements java.io.Serializable {

    private static final long serialVersionUID = 8995781005450591068L;

    @Field(required = true)
    private Integer subscriptionStatusId;
    @Field(required = true)
    private String subscriptionStatusCode;

    public HubSubscriptionStatus() {
    }

    public HubSubscriptionStatus(Integer subscriptionStatusId,
            String subscriptionStatusCode) {
        this.subscriptionStatusId = subscriptionStatusId;
        this.subscriptionStatusCode = subscriptionStatusCode;
    }

    public Integer getSubscriptionStatusId() {
        return subscriptionStatusId;
    }

    public void setSubscriptionStatusId(Integer subscriptionStatusId) {
        this.subscriptionStatusId = subscriptionStatusId;
    }

    public String getSubscriptionStatusCode() {
        return subscriptionStatusCode;
    }

    public void setSubscriptionStatusCode(String subscriptionStatusCode) {
        this.subscriptionStatusCode = subscriptionStatusCode;
    }

}
