package org.motechproject.hub.mds;

// Generated Apr 21, 2014 6:59:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * HubSubscriberTransaction generated by hbm2java
 */
@Entity
public class HubSubscriberTransaction implements java.io.Serializable {

	private static final long serialVersionUID = -2823908898058704053L;
	@Field(required=true)
	private int hubDistributionStatusId;
	
	
	@Field(required=true)
	private int hubSubscriptionId;
	
	@Field(required=true)
	private int retryCount;
	
	@Field
	private String content;
	
	public int getHubDistributionStatusId() {
		return hubDistributionStatusId;
	}

	public void setHubDistributionStatusId(int hubDistributionStatusId) {
		this.hubDistributionStatusId = hubDistributionStatusId;
	}

	public int getHubSubscriptionId() {
		return hubSubscriptionId;
	}

	public void setHubSubscriptionId(int hubSubscriptionId) {
		this.hubSubscriptionId = hubSubscriptionId;
	}

	public int getRetryCount() {
		return retryCount;
	}

	public void setRetryCount(int retryCount) {
		this.retryCount = retryCount;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getContentType() {
		return contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Field(required=true)
	private String contentType;

	public HubSubscriberTransaction() {
	}

	public HubSubscriberTransaction(
			int hubDistributionStatusId,
			int hubSubscriptionId, int retryCount, String contentType) {
		this.hubDistributionStatusId = hubDistributionStatusId;
		this.hubSubscriptionId = hubSubscriptionId;
		this.retryCount = retryCount;
		this.contentType = contentType;
	}

	public HubSubscriberTransaction(int hubDistributionStatusId,
			int hubSubscriptionId, int retryCount, String contentType,
			String content) {
		this.hubDistributionStatusId = hubDistributionStatusId;
		this.hubSubscriptionId = hubSubscriptionId;
		this.retryCount = retryCount;
		this.contentType = contentType;
		this.content = content;
	}

	

}
