package org.motechproject.batch.mds;

// Generated Apr 11, 2014 10:49:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.motechproject.batch.util.BatchConstants;

/**
 * BatchJobInstance generated by hbm2java
 */
@Entity
@Table(name = "batch_job_instance", schema = "batch", uniqueConstraints = @UniqueConstraint(columnNames = {
        "job_name", "job_key" }))
public class BatchJobInstance implements java.io.Serializable {

    private static final long serialVersionUID = -4773648658497934271L;
    private long jobInstanceId;
    private Long version;
    private String jobName;
    private String jobKey;
    private String createdBy;
    private String lastUpdatedBy;
    private Set<BatchJobExecution> batchJobExecutions = new HashSet<BatchJobExecution>(
            0);

    public BatchJobInstance() {
    }

    public BatchJobInstance(long jobInstanceId, String jobName, String jobKey) {
        this.jobInstanceId = jobInstanceId;
        this.jobName = jobName;
        this.jobKey = jobKey;
    }

    public BatchJobInstance(long jobInstanceId, String jobName, String jobKey,
            String createdBy, String lastUpdatedBy,
            Set<BatchJobExecution> batchJobExecutions) {
        this.jobInstanceId = jobInstanceId;
        this.jobName = jobName;
        this.jobKey = jobKey;
        this.createdBy = createdBy;
        this.lastUpdatedBy = lastUpdatedBy;
        this.batchJobExecutions = batchJobExecutions;
    }

    @Id
    @Column(name = "job_instance_id", unique = true, nullable = false)
    public long getJobInstanceId() {
        return this.jobInstanceId;
    }

    public void setJobInstanceId(long jobInstanceId) {
        this.jobInstanceId = jobInstanceId;
    }

    @Version
    @Column(name = "version")
    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Column(name = "job_name", nullable = false, length = BatchConstants.JOB_NAME_LENGTH)
    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    @Column(name = "job_key", nullable = false, length = BatchConstants.JOB_NAME_LENGTH)
    public String getJobKey() {
        return this.jobKey;
    }

    public void setJobKey(String jobKey) {
        this.jobKey = jobKey;
    }

    @Column(name = "created_by", length = BatchConstants.CREATED_BY_LENGTH)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "last_updated_by", length = BatchConstants.LAST_UPDATED_BY_LENGTH)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "batchJobInstance")
    public Set<BatchJobExecution> getBatchJobExecutions() {
        return this.batchJobExecutions;
    }

    public void setBatchJobExecutions(Set<BatchJobExecution> batchJobExecutions) {
        this.batchJobExecutions = batchJobExecutions;
    }

}
