package org.motechproject.batch.mds;

// Generated Apr 11, 2014 10:49:43 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BatchJobExecutionContext generated by hbm2java
 */
@Entity
@Table(name = "batch_job_execution_context", schema = "batch")
public class BatchJobExecutionContext implements java.io.Serializable {

	private long jobExecutionContextId;
	private String shortContext;
	private String serializedContext;
	private String createdBy;
	private String lastUpdatedBy;

	public BatchJobExecutionContext() {
	}

	public BatchJobExecutionContext(long jobExecutionContextId,
			String shortContext) {
		this.jobExecutionContextId = jobExecutionContextId;
		this.shortContext = shortContext;
	}

	public BatchJobExecutionContext(long jobExecutionContextId,
			String shortContext, String serializedContext, String createdBy,
			String lastUpdatedBy) {
		this.jobExecutionContextId = jobExecutionContextId;
		this.shortContext = shortContext;
		this.serializedContext = serializedContext;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@Column(name = "job_execution_context_id", unique = true, nullable = false)
	public long getJobExecutionContextId() {
		return this.jobExecutionContextId;
	}

	public void setJobExecutionContextId(long jobExecutionContextId) {
		this.jobExecutionContextId = jobExecutionContextId;
	}

	@Column(name = "short_context", nullable = false, length = 2500)
	public String getShortContext() {
		return this.shortContext;
	}

	public void setShortContext(String shortContext) {
		this.shortContext = shortContext;
	}

	@Column(name = "serialized_context")
	public String getSerializedContext() {
		return this.serializedContext;
	}

	public void setSerializedContext(String serializedContext) {
		this.serializedContext = serializedContext;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
