package org.motechproject.hub.mds.service;

import org.motechproject.hub.mds.HubDistributionContent;
import org.motechproject.mds.service.MotechDataService;


/**
 * This service provides data access for {@link org.motechproject.hub.domain.HubTopic}.
 * The implementation is generated by Motech Data Services and published as an OSGi service.
 */
public interface HubDistributionContentMDSService extends MotechDataService<HubDistributionContent> {

}
