package org.motechproject.config.mds;

import org.motechproject.config.domain.ModulePropertiesRecord;
import org.motechproject.mds.annotations.Lookup;
import org.motechproject.mds.annotations.LookupField;
import org.motechproject.mds.service.MotechDataService;

import java.util.List;

/**
 * This service provides data access for {@link org.motechproject.config.domain.ModulePropertiesRecord}.
 * The implementation is generated by Motech Data Services and published as an OSGi service.
 */
public interface BundlePropertiesDataService extends MotechDataService<ModulePropertiesRecord> {

    /**
     * Returns a list of {@code ModulePropertiesRecord}s matching given bundle symbolic name and file name.
     *
     * @param bundle  the bundle symbolic name
     * @param filename  the name of the file
     * @return list of {@code ModulePropertiesRecord}s
     */
    @Lookup(name = "By bundle and file name")
    List<ModulePropertiesRecord> findByBundleAndFileName(@LookupField(name = "bundle") String bundle,
                                                         @LookupField(name = "filename") String filename);
    /**
     * Returns list of {@code ModulePropertiesRecord}s matching given bundle symbolic name.
     *
     * @param bundle  the bundle symbolic name
     * @return list of {@code ModulePropertiesRecord}s
     */
    @Lookup(name = "By bundle")
    List<ModulePropertiesRecord> findByBundle(@LookupField(name = "bundle") String bundle);

}
