package org.motechproject.batch.model;

// Generated Apr 7, 2014 9:39:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.motechproject.batch.model.hibernate.BatchJobStatus;

/**
 * BatchJob generated by hbm2java
 */
public class BatchJob implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long jobId;
	private BatchJobStatus batchJobStatus;
	private String jobName;
	private String cronExpression;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;
	private Set batchJobConfigurationHistories = new HashSet(0);
	private Set batchJobParameterses = new HashSet(0);

	public BatchJob() {
	}

	public BatchJob(long jobId, BatchJobStatus batchJobStatus, String jobName,
			Date createTime) {
		this.jobId = jobId;
		this.batchJobStatus = batchJobStatus;
		this.jobName = jobName;
		this.createTime = createTime;
	}

	public BatchJob(long jobId, BatchJobStatus batchJobStatus, String jobName,
			String cronExpression, Date createTime, Date lastUpdated,
			String createdBy, String lastUpdatedBy,
			Set batchJobConfigurationHistories, Set batchJobParameterses) {
		this.jobId = jobId;
		this.batchJobStatus = batchJobStatus;
		this.jobName = jobName;
		this.cronExpression = cronExpression;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.batchJobConfigurationHistories = batchJobConfigurationHistories;
		this.batchJobParameterses = batchJobParameterses;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public BatchJobStatus getBatchJobStatus() {
		return this.batchJobStatus;
	}

	public void setBatchJobStatus(BatchJobStatus batchJobStatus) {
		this.batchJobStatus = batchJobStatus;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getCronExpression() {
		return this.cronExpression;
	}

	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Set getBatchJobConfigurationHistories() {
		return this.batchJobConfigurationHistories;
	}

	public void setBatchJobConfigurationHistories(
			Set batchJobConfigurationHistories) {
		this.batchJobConfigurationHistories = batchJobConfigurationHistories;
	}

	public Set getBatchJobParameterses() {
		return this.batchJobParameterses;
	}

	public void setBatchJobParameterses(Set batchJobParameterses) {
		this.batchJobParameterses = batchJobParameterses;
	}

}
