ALTER TABLE MOTECH_TASKS_TASKACTIONINFORMATION_VALUES MODIFY VALUE VARCHAR(500);
ALTER TABLE MOTECH_TASKS_TASKACTIONINFORMATION__HISTORY_VALUES MODIFY VALUE VARCHAR(500);
ALTER TABLE MOTECH_TASKS_TASKACTIONINFORMATION__TRASH_VALUES MODIFY VALUE VARCHAR(500);