-- Changing column 'MESSAGE' from VARCHAR(255) to MEDIUMTEXT

alter table MOTECH_TASKS_TASKERROR modify message MEDIUMTEXT NOT NULL;

alter table MOTECH_TASKS_TASKERROR__HISTORY modify message MEDIUMTEXT NOT NULL;

alter table MOTECH_TASKS_TASKERROR__TRASH modify message MEDIUMTEXT NOT NULL;