package org.motechproject.batch.model.hibernate;

// Generated Apr 11, 2014 10:49:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchJobStatus generated by hbm2java
 */
@Entity
@Table(name = "batch_job_status", schema = "batch")
public class BatchJobStatus implements java.io.Serializable {

	private long jobStatusId;
	private String jobStatusCode;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;
	private Set<BatchJob> batchJobs = new HashSet<BatchJob>(0);

	public BatchJobStatus() {
	}

	public BatchJobStatus(long jobStatusId, String jobStatusCode) {
		this.jobStatusId = jobStatusId;
		this.jobStatusCode = jobStatusCode;
	}

	public BatchJobStatus(long jobStatusId, String jobStatusCode,
			Date createTime, Date lastUpdated, String createdBy,
			String lastUpdatedBy, Set<BatchJob> batchJobs) {
		this.jobStatusId = jobStatusId;
		this.jobStatusCode = jobStatusCode;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
		this.batchJobs = batchJobs;
	}

	@Id
	@Column(name = "job_status_id", unique = true, nullable = false)
	public long getJobStatusId() {
		return this.jobStatusId;
	}

	public void setJobStatusId(long jobStatusId) {
		this.jobStatusId = jobStatusId;
	}

	@Column(name = "job_status_code", nullable = false, length = 100)
	public String getJobStatusCode() {
		return this.jobStatusCode;
	}

	public void setJobStatusCode(String jobStatusCode) {
		this.jobStatusCode = jobStatusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batchJobStatus")
	public Set<BatchJob> getBatchJobs() {
		return this.batchJobs;
	}

	public void setBatchJobs(Set<BatchJob> batchJobs) {
		this.batchJobs = batchJobs;
	}

}
