package org.motechproject.batch.model.hibernate;

// Generated Apr 11, 2014 10:49:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchJobParameters generated by hbm2java
 */
@Entity
@Table(name = "batch_job_parameters", schema = "batch")
public class BatchJobParameters implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long jobParametersId;
	private BatchJob batchJob;
	private String parameterName;
	private String parameterValue;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;

	public BatchJobParameters() {
	}

	public BatchJobParameters(long jobParametersId, BatchJob batchJob,
			String parameterName, Date createTime) {
		this.jobParametersId = jobParametersId;
		this.batchJob = batchJob;
		this.parameterName = parameterName;
		this.createTime = createTime;
	}

	public BatchJobParameters(long jobParametersId, BatchJob batchJob,
			String parameterName, String parameterValue, Date createTime,
			Date lastUpdated, String createdBy, String lastUpdatedBy) {
		this.jobParametersId = jobParametersId;
		this.batchJob = batchJob;
		this.parameterName = parameterName;
		this.parameterValue = parameterValue;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@Column(name = "job_parameters_id", unique = true, nullable = false)
	public long getJobParametersId() {
		return this.jobParametersId;
	}

	public void setJobParametersId(long jobParametersId) {
		this.jobParametersId = jobParametersId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id", nullable = false)
	public BatchJob getBatchJob() {
		return this.batchJob;
	}

	public void setBatchJob(BatchJob batchJob) {
		this.batchJob = batchJob;
	}

	@Column(name = "parameter_name", nullable = false, length = 100)
	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	@Column(name = "parameter_value", length = 100)
	public String getParameterValue() {
		return this.parameterValue;
	}

	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
