package org.motechproject.batch.model.hibernate;

// Generated Apr 11, 2014 10:49:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchJobConfigurationHistory generated by hbm2java
 */
@Entity
@Table(name = "batch_job_configuration_history", schema = "batch")
public class BatchJobConfigurationHistory implements java.io.Serializable {

	private Long jobConfigurationHistoryId;
	private BatchJob batchJob;
	private String jobConfiguration;
	private Date createTime;
	private Date lastUpdated;
	private String createdBy;
	private String lastUpdatedBy;

	public BatchJobConfigurationHistory() {
	}

	public BatchJobConfigurationHistory(Long jobConfigurationHistoryId,
			BatchJob batchJob, String jobConfiguration, Date createTime) {
		this.jobConfigurationHistoryId = jobConfigurationHistoryId;
		this.batchJob = batchJob;
		this.jobConfiguration = jobConfiguration;
		this.createTime = createTime;
	}

	public BatchJobConfigurationHistory(Long jobConfigurationHistoryId,
			BatchJob batchJob, String jobConfiguration, Date createTime,
			Date lastUpdated, String createdBy, String lastUpdatedBy) {
		this.jobConfigurationHistoryId = jobConfigurationHistoryId;
		this.batchJob = batchJob;
		this.jobConfiguration = jobConfiguration;
		this.createTime = createTime;
		this.lastUpdated = lastUpdated;
		this.createdBy = createdBy;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@Column(name = "job_configuration_history_id", unique = true, nullable = false)
	public Long getJobConfigurationHistoryId() {
		return this.jobConfigurationHistoryId;
	}

	public void setJobConfigurationHistoryId(Long jobConfigurationHistoryId) {
		this.jobConfigurationHistoryId = jobConfigurationHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id", nullable = false)
	public BatchJob getBatchJob() {
		return this.batchJob;
	}

	public void setBatchJob(BatchJob batchJob) {
		this.batchJob = batchJob;
	}

	@Column(name = "job_configuration", nullable = false)
	public String getJobConfiguration() {
		return this.jobConfiguration;
	}

	public void setJobConfiguration(String jobConfiguration) {
		this.jobConfiguration = jobConfiguration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "created_by", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by", length = 15)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
