#!/bin/sh

# Exit on non-zero exit code
set -e

# Create the motech user group
groupadd -f motech

# Create the motech user, if he doesn't exist
if [ `grep -c motech: /etc/passwd` -eq 0 ]; then
    useradd -r -c "Motech user" -d /usr/share/motech -g motech motech
fi

# Make motech the owner of relevant directories
chown -R motech:motech /var/log/motech
chown -R motech:motech /var/cache/motech
chown -R motech:motech /var/lib/motech
chown -R motech:motech /usr/share/motech/.motech

# Register motech service with udpate-rc.d
update-rc.d motech defaults 1>/dev/null
