#!/bin/sh

# Exit on non-zero exit code
set -e

# Unregister motech service from rc.d
update-rc.d -f motech remove 1>/dev/null

# Remove the cache folder, if it still exists
if [ -d /var/cache/motech ];then
    rm -r /var/cache/motech
fi

# Remove the log folder, if it still exists
if [ -d /var/log/motech ]; then
    rm -r /var/log/motech
fi

# Remove the webapps folder, if it still exists
if [ -d /var/lib/motech/webapps ]; then
    rm -r /var/lib/motech/webapps
fi