#!/bin/sh

# Exit on non-zero exit code
set -e

# Remove the cache folder, if it still exists
if [ -d /var/cache/motech/motech-default ]; then
    rm -r /var/cache/motech/motech-default
fi

# Remove the log folder, if it still exists
if [ -d /var/log/motech/motech-default ]; then
    rm -r /var/log/motech/motech-default
fi

# Remove the lib folder, if it still exists
if [ -d /var/lib/motech/motech-default ]; then
    rm -r /var/lib/motech/motech-default
fi

#Remove symlinks
rm -f /usr/share/motech/motech-default/logs
rm -f /usr/share/motech/motech-default/temp
rm -f /usr/share/motech/motech-default/work
rm -f /usr/share/motech/motech-default/webapps
rm -f /usr/share/motech/motech-default/.motech
rm -f /usr/share/motech/motech-default/felix-cache