#!/bin/sh

# Exit on non-zero exit code
set -e

# Remove the cache folder, if it still exists
if [ -d /var/cache/motech ]; then
    rm -r /var/cache/motech
fi

# Remove the log folder, if it still exists
if [ -d /var/log/motech ]; then
    rm -r /var/log/motech
fi

# Remove the lib folder, if it still exists
if [ -d /var/lib/motech ]; then
    rm -r /var/lib/motech
fi

#Remove symlinks
rm -f /usr/share/motech/logs
rm -f /usr/share/motech/temp
rm -f /usr/share/motech/work
rm -f /usr/share/motech/webapps
rm -f /usr/share/motech/.motech
rm -f /usr/share/motech/felix-cache