#!/bin/sh

# Exit on non-zero exit code
set -e

# Create symlinks
# logs
ln -s /var/log/motech/motech-default /usr/share/motech/motech-default/logs
# Cache
ln -s /var/cache/motech/motech-default/temp /usr/share/motech/motech-default/temp
ln -s /var/cache/motech/motech-default/work /usr/share/motech/motech-default/work
ln -s /var/cache/motech/motech-default/felix-cache /usr/share/motech/motech-default/felix-cache
# Data
ln -s /var/lib/motech/motech-default/webapps /usr/share/motech/motech-default/webapps
ln -s /var/lib/motech/motech-default/data /usr/share/motech/motech-default/.motech

# Map motech to /
mv /var/lib/motech/motech-default/webapps/motech-platform-server.war /var/lib/motech/motech-default/webapps/ROOT.war

# Register service
chkconfig --add motech

chmod 755 /usr/share/motech/motech-manage-tenants

if [ -d /usr/share/motech/motech-default/.motech ]; then
	chown -R motech-default:motech-default /var/lib/motech/motech-default/data
fi


