#!/bin/sh

# Exit on non-zero exit code
set -e

# Unregister service
chkconfig --del motech

# Remove fragment dir if empty
FRAGMENT_DIR=/usr/share/motech/motech-default/.motech/bundles/fragments

if [ -d $FRAGMENT_DIR ] && [ ! "$(ls -A $FRAGMENT_DIR)" ]; then
    rm -rf $FRAGMENT_DIR
fi

#if this is not update
if [ "$1" = 0 ]; then
    # Delete the motech user, if he exists
    if [ ! `grep -c motech-default: /etc/passwd` -eq 0 ]; then
        skill -KILL -u motech-default
        userdel motech-default
    fi
fi
