#!/bin/sh

# Exit on non-zero exit code
set -e

# Unregister service
chkconfig --del motech

# Delete the motech user, if he exists
if [ ! `grep -c motech: /etc/passwd` -eq 0 ]; then
    skill -KILL -u motech
    userdel motech
fi

#Remove symlinks
rm -f /usr/share/motech/logs
rm -f /usr/share/motech/temp
rm -f /usr/share/motech/work
rm -f /usr/share/motech/webapps
rm -f /usr/share/motech/.motech
rm -f /usr/share/motech/felix-cache
