#!/bin/sh

# Check if motech is running
invoke-rc.d motech status 1>/dev/null

if [ $? -eq 0 ]; then
    # Exit on non-zero exit code
    set -e
    # Restart the motech server
    invoke-rc.d motech restart
fi