#!/bin/sh

# Exit on non-zero exit code
set -e

# Create the motech user, if he doesn't exist
if [ `grep -c motech: /etc/passwd` -eq 0 ]; then
    useradd -r -c "Motech user" -d /usr/share/motech/motech motech
fi

# Make motech the owner of relevant directories
if [ -d /var/log/motech/motech ]; then
    chown -R motech:motech /var/log/motech/motech
fi
if [ -d /var/cache/motech/motech ]; then
    chown -R motech:motech /var/cache/motech/motech
fi
if [ -d /var/lib/motech/motech ]; then
    chown -R motech:motech /var/lib/motech/motech
fi

# Register motech service with udpate-rc.d
update-rc.d motech defaults 1>/dev/null

