#!/bin/sh

# Exit on non-zero exit code
set -e

# Unregister motech service from rc.d
update-rc.d -f motech remove 1>/dev/null

#if this is not update
if [ "$1" = remove ]; then
    # Delete the motech user, if he exists
    if [ ! `grep -c motech: /etc/passwd` -eq 0 ]; then
        userdel motech
    fi
fi
