#!/bin/sh

# Exit on non-zero exit code
set -e

# Remove fragment dir if empty
FRAGMENT_DIR=/usr/share/motech/.motech/bundles/fragments

if [ -d $FRAGMENT_DIR ] && [ ! "$(ls -A $FRAGMENT_DIR)" ]; then
    rm -rf $FRAGMENT_DIR
fi

# Stop the motech server
invoke-rc.d motech stop