#!/bin/sh

# Exit on non-zero exit code
set -e

# Stop the motech server
if [ -f /etc/init.d/motech ]; then
    invoke-rc.d motech stop
fi

# Remove fragment dir if empty
FRAGMENT_DIR=/var/lib/motech/motech/data/bundles/fragments

if [ -d $FRAGMENT_DIR ] && [ ! "$(ls -A $FRAGMENT_DIR)" ]; then
    rm -rf $FRAGMENT_DIR
fi

# Remove logs
rm -rf /var/log/motech/motech/

# Remove cache
rm -rf /var/cache/motech/motech/

# Remove lib
rm -rf /var/lib/motech/motech/



