#!/bin/sh

# Exit on non-zero exit code
set -e

# Stop the motech server
invoke-rc.d motech stop

# Delete the motech user, if he exists
if [ ! `grep -c motech: /etc/passwd` -eq 0 ]; then
    userdel motech
fi
