package org.motechproject.testing.osgi.mvn;

import org.springframework.core.io.Resource;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

/**
 * A class used for parsing the output of dependency lists generated by the list goal of the Maven dependency plugin.
 */
public final class MavenDependencyListParser {

    private MavenDependencyListParser() {
    }

    /**
     * Parses a list of dependencies into a collection of objects representing Maven artifacts.
     * @param resource the resource from which the dependency list should be read
     * @return the list of objects representing Maven artifacts
     * @throws IOException if there was an exception reading the dependencies list
     */
    public static List<MavenArtifact> parseDependencies(final Resource resource) throws IOException {
         return parseDependencies(new InputStreamReader(resource.getInputStream()));
    }

    /**
     * Parses a list of dependencies into a collection of objects representing Maven artifacts.
     * @param reader the reader from which the dependency list file will be read
     * @return the list of objects representing Maven artifacts
     * @throws IOException if there was an exception reading the dependencies list
     */
    public static List<MavenArtifact> parseDependencies(final InputStreamReader reader) throws IOException {
        BufferedReader in = new BufferedReader(reader);
        List<MavenArtifact> artifacts = new ArrayList<>();
        String line = in.readLine();
        while (line != null) {
            if (isSpecLine(line)) {
                artifacts.add(MavenArtifact.parse(line));
            }
            line = in.readLine();
        }
        return artifacts;
    }

    private static boolean isSpecLine(final String line) {
        if (line.contains("project: MavenProject:")) {
            return false;
        }

        int i = line.indexOf(':');
        if (i > 0) {
            // check for a second colon.
            i = line.indexOf(':', i + 1);
            if (i > 0) {
                // check for a third colon
                return (line.indexOf(':', i + 1) >= 0);
            }
        }
        return false;
    }
}
