package org.motechproject.mds.domain;

/**
 * The <code>FieldInfo</code> class contains base information about the given entity field like its
 * name or type.
 *
 * @see org.motechproject.mds.service.JarGeneratorService
 */
public class FieldInfo {
    private String name;
    private String displayName;
    private String type;
    private String taskType;
    private TypeInfo additionalTypeInfo;
    private boolean required;
    private boolean restExposed;
    private boolean autoGenerated;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isRequired() {
        return required;
    }

    public void setRequired(boolean required) {
        this.required = required;
    }

    public boolean isRestExposed() {
        return restExposed;
    }

    public void setRestExposed(boolean restExposed) {
        this.restExposed = restExposed;
    }

    public TypeInfo getAdditionalTypeInfo() {
        return additionalTypeInfo;
    }

    public void setAdditionalTypeInfo(TypeInfo additionalTypeInfo) {
        this.additionalTypeInfo = additionalTypeInfo;
    }

    public enum TypeInfo {
        ALLOWS_MULTIPLE_SELECTIONS
    }

    public String getTaskType() {
        return taskType;
    }

    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
}
