#!/bin/sh

# Create the motech user group
groupadd -f motech

# Create the motech user, if he doesn't exist
if [ `grep -c motech: /etc/passwd` -eq 0 ]; then
	useradd -r -c "Motech user" -d /usr/share/motech -g motech motech
fi
