ALTER TABLE "MOTECH_TASKS_TASKACTIONINFORMATION_VALUES" ALTER COLUMN "VALUE" TYPE VARCHAR(500);
ALTER TABLE "MOTECH_TASKS_TASKACTIONINFORMATION__HISTORY_VALUES" ALTER COLUMN "VALUE" TYPE VARCHAR(500);
ALTER TABLE "MOTECH_TASKS_TASKACTIONINFORMATION__TRASH_VALUES" ALTER COLUMN "VALUE" TYPE VARCHAR(500);