DROP PROCEDURE IF EXISTS deleteActiveColumn;

DELIMITER //
CREATE PROCEDURE deleteActiveColumn()
BEGIN

IF EXISTS (SELECT * FROM information_schema.columns WHERE table_name = 'MOTECH_WEB_SECURITY_MOTECHUSER' AND column_name = 'active') THEN

UPDATE MOTECH_WEB_SECURITY_MOTECHUSER
SET userStatus = "ACTIVE"
WHERE active = 1;

UPDATE MOTECH_WEB_SECURITY_MOTECHUSER
SET userStatus = "BLOCKED"
WHERE active = 0;

ALTER TABLE MOTECH_WEB_SECURITY_MOTECHUSER DROP COLUMN `active`;

END IF;

IF EXISTS (SELECT * FROM information_schema.columns WHERE table_name = 'MOTECH_WEB_SECURITY_MOTECHUSER__HISTORY' AND column_name = 'active') THEN

ALTER TABLE MOTECH_WEB_SECURITY_MOTECHUSER__HISTORY DROP COLUMN `active`;

END IF;

IF EXISTS (SELECT * FROM information_schema.columns WHERE table_name = 'MOTECH_WEB_SECURITY_MOTECHUSER__TRASH' AND column_name = 'active') THEN

ALTER TABLE MOTECH_WEB_SECURITY_MOTECHUSER__TRASH DROP COLUMN `active`;

END IF;

END//

DELIMITER ;

CALL deleteActiveColumn();

DROP PROCEDURE IF EXISTS deleteActiveColumn;