import org.motechproject.tama.model.Patient
import org.motechproject.tama.model.Regimen

global java.util.Map resultMap;

rule "age > 50, taking Prescription Regimen 1, in TAMA program > 6 months"
when
    Patient( age > 50, regimen == Regimen.REGIMEN_1, daysSinceRegistered > 180 )
then
	resultMap.put("treeName", "age-over-50-regimen1-registered-over-180");
end

rule "NOT age > 50 OR NOT taking Prescription Regimen 1 OR NOT in TAMA program > 6 months"
when
    not Patient( age > 50, regimen == Regimen.REGIMEN_1, daysSinceRegistered > 180 )
then
	resultMap.put("treeName", "age-under-50-or-non-regimen1-or-registered-less-than-180");
end